export const INITIATE_API = 'INITIATE_API';
export const INITIATE_API_SUCCESS = 'INITIATE_API_SUCCESS';
export const INITIATE_API_FAILED = 'INITIATE_API_FAILED';

export const MEMBER_STATE_DATA = 'MEMBER_STATE_DATA';
export const MEMBER_STATE_SUCCESS = 'MEMBER_STATE_SUCCESS';
export const MEMBER_STATE_FAILED = 'MEMBER_STATE_FAILED';

export const UNIVERSAL_FEED_DATA = 'UNIVERSAL_FEED_DATA';
export const UNIVERSAL_FEED_FAILED = 'UNIVERSAL_FEED_FAILED';
export const UNIVERSAL_FEED_SUCCESS = 'UNIVERSAL_FEED_SUCCESS';
export const UNIVERSAL_FEED_REFRESH_SUCCESS = 'UNIVERSAL_FEED_REFRESH_SUCCESS';

export const LIKE_POST = 'LIKE_POST';
export const LIKE_POST_FAILED = 'LIKE_POST_FAILED';
export const LIKE_POST_SUCCESS = 'LIKE_POST_SUCCESS';
export const LIKE_POST_STATE = 'LIKE_POST_STATE';

export const SAVE_POST = 'SAVE_POST';
export const SAVE_POST_FAILED = 'SAVE_POST_FAILED';
export const SAVE_POST_SUCCESS = 'SAVE_POST_SUCCESS';
export const SAVE_POST_STATE = 'SAVE_POST_STATE';

export const REPORT_TAGS_DATA = 'REPORT_TAGS_DATA';
export const REPORT_TAGS_FAILED = 'REPORT_TAGS_FAILED';
export const REPORT_TAGS_SUCCESS = 'REPORT_TAGS_SUCCESS';

export const POST_REPORT = 'POST_REPORT';
export const POST_REPORT_FAILED = 'POST_REPORT_FAILED';
export const POST_REPORT_SUCCESS = 'POST_REPORT_SUCCESS';

export const POST_DELETE = 'POST_DELETE';
export const POST_DELETE_FAILED = 'POST_DELETE_FAILED';
export const POST_DELETE_SUCCESS = 'POST_DELETE_SUCCESS';
export const DELETE_POST_STATE = 'DELETE_POST_STATE';

export const PIN_POST = 'PIN_POST';
export const PIN_POST_FAILED = 'PIN_POST_FAILED';
export const PIN_POST_SUCCESS = 'PIN_POST_SUCCESS';
export const PIN_POST_STATE = 'PIN_POST_STATE';

export const AUTO_PLAY_POST_VIDEO = 'AUTO_PLAY_POST_VIDEO';

export const POST_LIKES_DATA = 'POST_LIKES_DATA';
export const POST_LIKES_FAILED = 'POST_LIKES_FAILED';
export const POST_LIKES_SUCCESS = 'POST_LIKES_SUCCESS';
export const POST_LIKES_CLEAR = 'POST_LIKES_CLEAR';

export const DECODE_URL_DATA = 'DECODE_URL_DATA';
export const DECODE_URL_FAILED = 'DECODE_URL_FAILED';
export const DECODE_URL_SUCCESS = 'DECODE_URL_SUCCESS';

export const CREATE_POST = 'CREATE_POST';
export const CREATE_POST_FAILED = 'CREATE_POST_FAILED';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';

export const EDIT_POST = 'EDIT_POST';
export const EDIT_POST_FAILED = 'EDIT_POST_FAILED';
export const EDIT_POST_SUCCESS = 'EDIT_POST_SUCCESS';

export const EDIT_COMMENT = 'EDIT_COMMENT';
export const EDIT_COMMENT_FAILED = 'EDIT_COMMENT_FAILED';
export const EDIT_COMMENT_SUCCESS = 'EDIT_COMMENT_SUCCESS';
export const EDIT_COMMENT_STATE = 'EDIT_COMMENT_STATE';

export const POST_DATA = 'POST_DATA';
export const POST_DATA_FAILED = 'POST_DATA_FAILED';
export const POST_DATA_SUCCESS = 'POST_DATA_SUCCESS';

export const POST_COMMENTS = 'POST_COMMENTS';
export const POST_COMMENTS_FAILED = 'POST_COMMENTS_FAILED';
export const POST_COMMENTS_SUCCESS = 'POST_COMMENTS_SUCCESS';

export const LIKE_COMMENT = 'LIKE_COMMENT';
export const LIKE_COMMENT_FAILED = 'LIKE_COMMENT_FAILED';
export const LIKE_COMMENT_SUCCESS = 'LIKE_COMMENT_SUCCESS';

export const COMMENT_LIKES_DATA = 'COMMENT_LIKES_DATA';
export const COMMENT_LIKES_FAILED = 'COMMENT_LIKES_FAILED';
export const COMMENT_LIKES_SUCCESS = 'COMMENT_LIKES_SUCCESS';

export const CREATE_COMMENT = 'CREATE_COMMENT';
export const CREATE_COMMENT_FAILED = 'CREATE_COMMENT_FAILED';
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const CREATE_COMMENT_STATE = 'CREATE_COMMENT_STATE';

export const CREATE_REPLY = 'CREATE_REPLY';
export const CREATE_REPLY_FAILED = 'CREATE_REPLY_FAILED';
export const CREATE_REPLY_SUCCESS = 'CREATE_REPLY_SUCCESS';
export const CREATE_REPLY_STATE = 'CREATE_REPLY_STATE';

export const CLEAR_COMMENT = 'CLEAR_COMMENT';

export const CLEAR_POST = 'CLEAR_POST';

export const COMMENT_DELETE = 'COMMENT_DELETE';
export const COMMENT_DELETE_FAILED = 'COMMENT_DELETE_FAILED';
export const COMMENT_DELETE_SUCCESS = 'COMMENT_DELETE_SUCCESS';
export const DELETE_COMMENT_STATE = 'DELETE_COMMENT_STATE';

export const UPLOAD_ATTACHMENTS = 'UPLOAD_ATTACHMENTS';
export const CLEAR_FEED = 'CLEAR_FEED';

export const TAGGING_LIST_DATA = 'TAGGING_LIST_DATA';
export const TAGGING_LIST_FAILED = 'TAGGING_LIST_FAILED';
export const TAGGING_LIST_SUCCESS = 'TAGGING_LIST_SUCCESS';

export const POST_DATA_REFRESH = 'POST_DATA_REFRESH';
export const POST_DATA_REFRESH_FAILED = 'POST_DATA_REFRESH_FAILED';
export const POST_DATA_REFRESH_SUCCESS = 'POST_DATA_REFRESH_SUCCESS';
