export type ActionTypes =
  | "INIT_API_SUCCESS"
  | "PROFILE_DATA_SUCCESS"
  | "UNIVERSAL_FEED_SUCCESS"
  | "UNIVERSAL_FEED_REFRESH_SUCCESS"
  | "DELETE_POST_STATE"
  | "POST_DELETE_SUCCESS"
  | "DELETE_COMMENT_STATE"
  | "COMMENT_DELETE_SUCCESS"
  | "REPORT_TAGS_SUCCESS"
  | "PIN_POST_STATE"
  | "START_LOADING"
  | "STOP_LOADING";

export const INIT_API_SUCCESS: ActionTypes = "INIT_API_SUCCESS";
export const PROFILE_DATA_SUCCESS: ActionTypes = "PROFILE_DATA_SUCCESS";
export const UNIVERSAL_FEED_SUCCESS: ActionTypes = "UNIVERSAL_FEED_SUCCESS";
export const UNIVERSAL_FEED_REFRESH_SUCCESS: ActionTypes =
  "UNIVERSAL_FEED_REFRESH_SUCCESS";
export const DELETE_POST_STATE: ActionTypes = "DELETE_POST_STATE";
export const POST_DELETE_SUCCESS: ActionTypes = "POST_DELETE_SUCCESS";
export const DELETE_COMMENT_STATE: ActionTypes = "DELETE_COMMENT_STATE";
export const COMMENT_DELETE_SUCCESS: ActionTypes = "COMMENT_DELETE_SUCCESS";
export const REPORT_TAGS_SUCCESS: ActionTypes = "REPORT_TAGS_SUCCESS";
export const PIN_POST_STATE: ActionTypes = "PIN_POST_STATE";
export const START_LOADING: ActionTypes = "START_LOADING";
export const STOP_LOADING: ActionTypes = "STOP_LOADING";
